[project]
name = "ostr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Orion Hess", email = "orionhess@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "importlib>=1.0.4",
    "pytest>=9.0.3",
]

[project.scripts]
ostr = "ostr:main"

[build-system]
requires = ["uv_build>=0.11.7,<0.12.0"]
build-backend = "uv_build"
